### PR TITLE
Fix dual parenting and hierarchy loop prevention (fix #113)

### LINKED ISSUE #113: Dealing with dual parenting
At the moment, is possible to assign the same anchor to two different parents. We need to define:
1. Address these cases when required (such as the Align Anchors command), or
2. Limit the availability in the 'Insert Join' command (ie, do not show any layers already used as anchors in other tilesets).
3. Other?

### PR DESCRIPTION
**Pull request by Gasparoken**

### CODE REVIEW

**Comment by Gasparoken** [comment]
Ready for review. Added description to commit.

**Comment by Gasparoken** [comment]
Bug found during manual testing on swap_hierarchy. Not ready for review.

**Comment by Gasparoken** [comment]
Ready for review.

**Comment by dacap** [comment]
Merged in 71c297f1143ce711d102bc643f4fc3f38f3ab0fa with minor formatting changes

**Pull request closed without merging**
