### PR TITLE
Edit Attachment improvements (fix #65)

### PR DESCRIPTION
**Pull request by Gasparoken**
fix #65

### CODE REVIEW

**Comment by dacap** [comment]
Just a little note: it looks like this PR include the change in https://github.com/aseprite/Attachment-System/commit/1bb1b051cb323edfa1e11ab2302b7c14bbb1adac

**Comment by Gasparoken** [comment]
> Just a little note: it looks like this PR include the change in https://github.com/aseprite/Attachment-System/commit/1bb1b051cb323edfa1e11ab2302b7c14bbb1adac

Thanks. I just removed that change.

**Comment by dacap** [comment]
After rebasing to `main` I got this error when trying to the edit attachments of a specific file:
```
plugin.lua:195: attempt to index a nil value (field 'tileset')
```
Pushed the commit to `issue-65b` branch so you can continue from there: https://github.com/aseprite/Attachment-System/tree/issue-65b

**Comment by Gasparoken** [comment]
Pushed the fix on branch `issue-65b` (https://github.com/aseprite/Attachment-System/pull/84)

**Comment by Gasparoken** [comment]
In the specific file there is another error in `Edit Anchors`. I will push the solution here soon.

**Comment by Gasparoken** [comment]
Fixes pushed on https://github.com/aseprite/Attachment-System/pull/84.

The 'Edit Anchor fix' is related with the presence of attachments without the corresponding anchors (which are present in the other attachments in the same tileset). An attachment/s with a different set of anchors (or no anchors) could have been generated in earlier versions of the Attachment System.

**Comment by dacap** [comment]
Merged with #84

**Pull request closed without merging**
